AllCops:
  Exclude:
    - "bin/**/*"
    - "db/**/*"
    - "config/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "app/assets/**/*"
    - "db/schema.rb"
  TargetRubyVersion: 3.2.1
  DisplayCopNames: true
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "lib/tasks/**/*"

Style/Documentation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/FormatString:
  Exclude:
    - "app/components/**/*"
Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/NumericPredicate:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/LineLength:
  Max: 100
  AllowedPatterns: ['(\A|\s)#']
  Exclude:
    - "spec/**/*"

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Max: 21

Style/AsciiComments:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Bundler/OrderedGems:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: false

Style/CaseLikeIf:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashLikeCase:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Layout/BeginEndAlignment:
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/ConstantDefinitionInBlock: # (new in 0.91)
  Enabled: true

Lint/DuplicateRequire: # (new in 0.90)
  Enabled: true

Lint/DuplicateRescueException: # (new in 0.89)
  Enabled: true

Lint/EmptyConditionalBody: # (new in 0.89)
  Enabled: true

Lint/EmptyFile: # (new in 0.90)
  Enabled: true

Lint/FloatComparison: # (new in 0.89)
  Enabled: true

Lint/IdentityComparison:
  Enabled: true

Lint/MissingSuper: # (new in 0.89)
  Enabled: true

Lint/OutOfRangeRegexpRef: # (new in 0.89)
  Enabled: true

Lint/SelfAssignment: # (new in 0.89)
  Enabled: true

Lint/TopLevelReturnWithArgument: # (new in 0.89)
  Enabled: true

Lint/TrailingCommaInAttributeDeclaration: # (new in 0.90)
  Enabled: true

Lint/UnreachableLoop: # (new in 0.89)
  Enabled: true

Lint/UselessMethodDefinition: # (new in 0.90)
  Enabled: true

Lint/UselessTimes: # (new in 0.91)
  Enabled: true

Style/CombinableLoops:
  Enabled: true

Style/ExplicitBlockArgument: # (new in 0.89)
  Enabled: true

Style/GlobalStdStream: # (new in 0.89)
  Enabled: true

Style/KeywordParametersOrder: # (new in 0.90)
  Enabled: true

Style/OptionalBooleanParameter: # (new in 0.89)
  Enabled: true

Style/RedundantSelfAssignment: # (new in 0.90)
  Enabled: true

Style/SingleArgumentDig: # (new in 0.89)
  Enabled: true

Style/SoleNestedConditional: # (new in 0.89)
  Enabled: true

Style/StringConcatenation:
  Enabled: true
